{{- range .Values.ingress.routes }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $.Release.Name }}-ingress-route-{{ .id }}"
spec:
  entryPoints:
    - web
  routes:
    - match: {{ .match }}
      kind: Rule
      services:
        - name: {{ $.Release.Name }}
          port: {{ $.Values.service.externalPort }}
      middlewares:
        - name: "{{ $.Release.Name }}-ingress-route-{{ .id }}-path-rewriter"
      {{ if .priority }}priority: {{ .priority }}{{ end }}
{{ if .middlewareSpec }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ $.Release.Name }}-ingress-route-{{ .id }}-path-rewriter"
spec: {{- .middlewareSpec | toYaml | trim | nindent 2 }}
{{ end }}
---
{{- end }}
