apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: simpleingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/login`)
      kind: Rule
      services:
        - name: {{ $.Release.Name }}
          port: {{ $.Values.service.externalPort }}
      middlewares:
        - name: test-replacepathregex
          namespace: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test-replacepathregex
spec:
  replacePathRegex:
    regex: ^/login(.*)
    replacement: /api/pages/login
