apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-customer-account-service
  labels:
    app: adp-customer-account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adp-customer-account-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: adp-customer-account-service
    spec:
      containers:
        - name: adp-customer-account-service
          image: ardalo/adp-customer-account-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 700Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 300m
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /alive
              port: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adp-customer-account-service
  labels:
    app: adp-customer-account-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: adp-customer-account-service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/projectcontour/contour
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: contour
spec:
  gatewayClassName: contour
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: contour
data:
  contour.yaml: |
    gateway:
      controllerName: projectcontour.io/projectcontour/contour
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: adp-customer-account-service-alive
spec:
  parentRefs:
    - name: contour
  rules:
    - matches:
        - path:
            value: /alive
      backendRefs:
        - name: adp-customer-account-service
          port: 80
