replicaCount: 1
rollingUpdateMaxSurge: 1
rollingUpdateMaxUnavailable: 1

image:
  repository: overridden_during_deployment_via_helm_upgrade
  tag: overridden_during_deployment_via_helm_upgrade
  pullPolicy: Always

app:
  internalPort: 8080
  minMemory: 700Mi
  maxMemory: 1Gi
  minCpu: 100m
  maxCpu: 300m
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 30
    path: /alive
    port: 8080
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    path: /ready
    port: 8080

service:
  externalPort: 80

ingress:
  className: traefik
  routes:
    - id: login
      match: Path(`/login`)
      middlewareSpec:
        replacePath:
          path: /api/pages/login
    - id: register
      match: Path(`/register`)
      middlewareSpec:
        replacePath:
          path: /api/pages/register
    - id: my-account
      match: Path(`/my/account`)
      middlewareSpec:
        replacePath:
          path: /api/pages/my-account
    - id: global-404
      match: PathPrefix(`/`)
      priority: 1
      middlewareSpec:
        replacePath:
          path: /api/pages/global-404
