name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - run: ./gradlew build --no-daemon
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push tagged Docker image
        if: github.event_name == 'push'
        run: |
         ./gradlew bootBuildImage --imageName=ardalo/adp-customer-account-service:${{ github.sha }}
         docker push ardalo/adp-customer-account-service:${{ github.sha }}
      - name: Build and push latest Docker image
        if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
        run: |
          ./gradlew bootBuildImage --imageName=ardalo/adp-customer-account-service:latest
          docker push ardalo/adp-customer-account-service:latest
