name: Deploy to Google K8s Engine

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: adp-customer-account-service

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      # Authenticate via Service Account Key JSON. Use Workload Identity Federation in the future
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy
        run: |-
          kubectl apply -f deployment/k8s/deployment.yml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
