name: Deploy to Google K8s Engine

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: autopilot-cluster-1
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: adp-customer-account-service

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Deploy
        timeout-minutes: 6
        run: |-
          helm upgrade $DEPLOYMENT_NAME deployment/helm \
            --atomic \
            --cleanup-on-fail \
            --debug \
            --install \
            --timeout 4m \
            --values deployment/helm/values.yml \
            --wait
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
